# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            AK's blog
tagline:          '「总有失落，追求的心不会沉沦漂泊！」'
description:      '<img src="https://avatars0.githubusercontent.com/u/1425193?s=140">'
url:              http://akzhou.github.io
paginate:         5
homepage:	      个人主页

author:
  name:           'AK'
  url:            http://akzhou.github.io

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/akzhou
